---
- name: with_items 예시
  hosts: localhost
  tasks:
    - name: 여러 패키지 설치
      apt:
        name: "{{ item }}"
        state: present
        with_items:
          - nginx
          - curl
          - git
