- name: Install and configure Nginx on Ubuntu
  hosts: ec2
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure the directory exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Create index.html with "hello"
      copy:
        dest: /var/www/html/index.html
        content: "hello"
        mode: '0644'

    - name: Test nginx configuration
      command: nginx -t

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

