- name: Install and configure Nginx with 2 virtual hosts on Ubuntu
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Create the configuration for naver.com
      copy:
        dest: /etc/nginx/sites-available/naver.com
        content: |
          server {
              listen 80;
              server_name naver.com www.naver.com;

              root /var/www/naver;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
    
    - name: Create the configuration for google.com
      copy:
        dest: /etc/nginx/sites-available/google.com
        content: |
          server {
              listen 80;
              server_name google.com www.google.com;

              root /var/www/google;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Enable naver.com site
      file:
        src: /etc/nginx/sites-available/naver.com
        dest: /etc/nginx/sites-enabled/naver.com
        state: link

    - name: Enable google.com site
      file:
        src: /etc/nginx/sites-available/google.com
        dest: /etc/nginx/sites-enabled/google.com
        state: link

    - name: Create directory for naver.com
      file:
        path: /var/www/naver
        state: directory

    - name: Create directory for google.com
      file:
        path: /var/www/google
        state: directory

    - name: Create index.html for naver.com
      copy:
        dest: /var/www/naver/index.html
        content: "Welcome to naver.com"
    
    - name: Create index.html for google.com
      copy:
        dest: /var/www/google/index.html
        content: "Welcome to google.com"

    - name: Test nginx configuration
      command: nginx -t

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
